[package]
name = "fcrypt"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10.3"
blake3 = "1.5.5"
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["full"] }
rand = "0.8"
rayon = "1.10.0"
walkdir = "2.5.0"

[dev-dependencies]
tempfile = "3.8"
